# Generated by Django 5.0.1 on 2024-03-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='updaate_date',
            new_name='update_date',
        ),
    ]
